config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :candidatos
  get 'users/new'

  root  :to => 'users#new'
  
resources :user_sessions
resources :users
get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end
end

app/models/consultaCandidatos.rb
 class ConsultaCandidatos < ActiveRecord::Base
 end

app/controllers/ConsultaCandidatos_controller.rb
class ConsultaCandidatosController < ApplicationController

  def consultaCandidatos                                              
    @consultaCandidatos = Candidates.all
  end
  
  def candidate_params
        params.require(:candidate).permit(:nome, :partido, :numero)
  end
  def new
    # default: render ’new’ template
  end
  def create
    @candidate = candidate.create!(params[:candidate])
    flash[:notice] = "#{@candidates.nome} was successfully created."
    redirect_to candidate_path
  end
  def update
    @candidate = candidate.find params[:id]
    @candidate.update_attributes!(params[:candidate])
    flash[:notice] = "#{@candidate.nome} was successfully updated."
    redirect_to candidate_path(@candidate)
  end
  def destroy
    @candidate = candidate.find(params[:id])
    @candidate.destroy
    flash[:notice] = "Candidate ’#{@candidate.nome}’ deleted."
    redirect_to candidate_path
  end
end

app/controllers/consultaCandidatos_controller.rb
class ConsultaCandidatosController < ApplicationController

  def consultaCandidatos                                              
    @consultaCandidatos = Candidates.all
  end
  
  def candidate_params
        params.require(:candidate).permit(:nome, :partido, :numero)
  end
  def new
    # default: render ’new’ template
  end
  def create
    @candidate = candidate.create!(params[:candidate])
    flash[:notice] = "#{@candidates.nome} was successfully created."
    redirect_to candidate_path
  end
  def update
    @candidate = candidate.find params[:id]
    @candidate.update_attributes!(params[:candidate])
    flash[:notice] = "#{@candidate.nome} was successfully updated."
    redirect_to candidate_path(@candidate)
  end
  def destroy
    @candidate = candidate.find(params[:id])
    @candidate.destroy
    flash[:notice] = "Candidate ’#{@candidate.nome}’ deleted."
    redirect_to candidate_path
  end
end

app/views/ConsultaCandidatos/delete.html.haml
 = link_to ’Delete’, candidate_path(@candidate), :method => :delete
 = button_to ’Delete’, candidate_path(@candidate), :method => :delete,
:confirm => ’Are you sure?’

app/views/ConsultaCandidatos/index.html.haml
%h2 All candidatos

%table#candidatos
 %thead
  %tr
   %th candidatos Nome
   %th Numero
   %th Partido
   %th Propostas
 %tbody
  - @candidatos.each do |candidatos|
   %tr
    %td= candidatos.nome
    %td= candidatos.numero
    %td= candidatos.partido
    %td= link_to "More about #{candidatos.propostas}", candidatos_path(candidatos)
    = link_to ’Add new candidatos’, new_candidatos_path

app/views/ConsultaCandidatos/new.html.haml
%h2 Create New Candidates
= form_tag candidatos_path, :method => :post do
    = label :candidates, :nome, ’Nome’
    = text_field :candidates, :nome
    = label :candidates, :numero, ’Numero’
    = select :candidates, :numero, [’25’,’40’,’13’]
    = label :candidates, :partido, ’partido’
    = select :candidates, :partido
    = submit_tag ’Save Changes’

app/views/ConsultaCandidatos/show.html.haml
%h2 Details about #{@candidatos.nome}

    %ul#details
        %li
            Partido:
            = @candidatos.partido
        %li
            Numero:
            = @candidatos.numero
    %h3 Propostas:
    %p#propostas= @candidatos.propostas
    = link_to ’Back to candidatos list’, candidatos_path