config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :candidatos
  get 'users/new'

  root  :to => 'users#new'
  
resources :user_sessions
resources :users
get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end
end

app/models/candidato.rb
class Candidato < ActiveRecord::Base
end

app/controllers/candidatos_controller.rb
class CandidatosController < ApplicationController
  before_action :set_candidato, only: [:show, :edit, :update, :destroy]

  # GET /candidatos
  # GET /candidatos.json
  def index
    @candidatos = Candidato.all
  end

  # GET /candidatos/1
  # GET /candidatos/1.json
  def show
  end

  # GET /candidatos/new
  def new
    #@candidato = Candidato.new
  end

  # GET /candidatos/1/edit
  def edit
  end

  # POST /candidatos
  # POST /candidatos.json
  def create
    @candidato = Candidato.new(candidato_params)

    respond_to do |format|
      if @candidato.save
        format.html { redirect_to @candidato, notice: 'Candidato was successfully created.' }
        format.json { render :show, status: :created, location: @candidato }
      else
        format.html { render :new }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidatos/1
  # PATCH/PUT /candidatos/1.json
  def update
    respond_to do |format|
      if @candidato.update(candidato_params)
        format.html { redirect_to @candidato, notice: 'Candidato was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidato }
      else
        format.html { render :edit }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidatos/1
  # DELETE /candidatos/1.json
  def destroy
    @candidato.destroy
    respond_to do |format|
      format.html { redirect_to candidatos_url, notice: 'Candidato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidato
      @candidato = Candidato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidato_params
      params.require(:candidato).permit(:nome, :numero, :partido)
    end
end

app/helpers/candidatos_helper.rb
module CandidatosHelper
end

app/views/candidatos/_form.html.erb
<%= form_for(@candidato) do |f| %>
  <% if @candidato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidato.errors.count, "error") %> prohibited this candidato from being saved:</h2>

      <ul>
      <% @candidato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="field">
    <%= f.label :partido %><br>
    <%= f.text_field :partido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidatos/edit.html.erb
<h1>Editing Candidato</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidato %> |
<%= link_to 'Back', candidatos_path %>

app/views/candidatos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Candidatos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Numero</th>
      <th>Partido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidatos.each do |candidato| %>
      <tr>
        <td><%= candidato.nome %></td>
        <td><%= candidato.numero %></td>
        <td><%= candidato.partido %></td>
        <td><%= link_to 'Show', candidato %></td>
        <td><%= link_to 'Edit', edit_candidato_path(candidato) %></td>
        <td><%= link_to 'Destroy', candidato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidato', new_candidato_path %>

app/views/candidatos/new.html.erb
<h1>New Candidato</h1>

<%= render 'form' %>

<%= link_to 'Back', candidatos_path %>

app/views/candidatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @candidato.nome %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @candidato.numero %>
</p>

<p>
  <strong>Partido:</strong>
  <%= @candidato.partido %>
</p>

<%= link_to 'Edit', edit_candidato_path(@candidato) %> |
<%= link_to 'Back', candidatos_path %>