config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :candidatos
  get 'users/new'

  root  :to => 'users#new'
  
resources :user_sessions
resources :users
get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end
end

app/models/user_session.rb
class UserSession < ActiveRecord::Base
form_for(@user)
form_for(:session, url: login_path)
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:login], params[:password])
      redirect_back_or_to(:users, notice: 'Login realizado com sucesso!')
    else
      flash.now[:alert] = 'Falha no Login!'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :login %><br />
    <%= text_field_tag :login %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Sessions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_sessions.each do |user_session| %>
      <tr>
        <td><%= link_to 'Show', user_session %></td>
        <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
        <td><%= link_to 'Destroy', user_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<h1>New User Session</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>